using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OwnedDoNotSupportComplex;

public class Company
{
    public int Id { get; set; }
    public required string Name { get; set; }

    public IEnumerable<Contact> Contacts { get; set; } = [];
}

public class Contact
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public required string Name { get; set; }
    public required string Email { get; set; }

    public required Address Address { get; set; }
}

[ComplexType]
public class Address
{
    public required string Country { get; set; }
    public required string State { get; set; }
    public required string ZipCode { get; set; }

    public string? City { get; set; }
    public string? Street { get; set; }
}

public partial class FaultyDataContext : DbContext
{
    public FaultyDataContext(DbContextOptions<FaultyDataContext> options)
        : base(options) { }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        builder.Entity<Company>(e =>
        {
            e.OwnsMany(
                x => x.Contacts,
                o =>
                {
                    o.WithOwner().HasPrincipalKey(x => x.Id).HasForeignKey(x => x.CompanyId);
                    // ------------------------------------------------------------
                    // Running dotnet-ef to generate Migration for this code sample
                    // generate a faulty code which tries to apply ComplexProperty:

                    // o.ComplexProperty(x => x.Address);

                    // but it causes build issues cause the function doesn't exist:

                    /* Similar error will appear in code generated by migration:
                    'OwnedNavigationBuilder<Company, Contact>' does not contain a definition for 'ComplexProperty' and no accessible extension method 'ComplexProperty' accepting a first argument of type 'OwnedNavigationBuilder<Company, Contact>' could be found (are you missing a using directive or an assembly reference?)
                    */
                }
            );
        });
    }
}
